---
title: "HW06"
author: "Oksana Ivanova"
date: "3 May 2019"
output: pdf_document
---

```{r warning=FALSE, message=FALSE}
set.seed(42)
library(gapminder)
library(ggplot2)
library(datasets)
library(dplyr)
```

#Task#1
```{r}
df1 <- iris %>%
  transmute(Species, Part = 'sepal', Length = Sepal.Length, Width = Sepal.Width,
              id = as.numeric(row.names(iris)))
df2 <- iris %>%
  transmute(Species, Part = 'petal', Length = Petal.Length, Width = Petal.Width, 
              id =  as.numeric(row.names(iris)))
iris_long <- bind_rows(df1, df2) %>%
  arrange(id)
iris_long$id <- NULL
```

```{r}
ggplot(iris_long, aes(x = Length, y = Width, color = Part)) +
  geom_point(shape = 20)
```

```{r}
ggplot(iris_long, aes(x = Length, y = Width, fill = Part, size = Length + Width)) +
  geom_point(shape = 21) +
  facet_grid(Species ~ .) +
  theme_dark()
```


#Task#2
```{r}
df <- gapminder %>%
  filter(year == 2007)

ggplot(df, aes(x = gdpPercap, y = lifeExp, color = continent, size = pop)) +
  geom_point() + 
  scale_x_log10(breaks = c(1000, 10000))
```

```{r}
df <- gapminder %>%
  group_by(year, continent) %>%
  summarize(meanLifeExp = mean(lifeExp), totalPop = sum(pop) / 1000000)
df
```

```{r}
ggplot(df, aes(x = year, color = continent)) +
  geom_point(aes(y = meanLifeExp)) +
  geom_line(aes(y = meanLifeExp)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 85)) +
  scale_x_continuous(breaks = seq(1952, 2007, by = 5))
```

```{r}
ggplot(df, aes(x = year, color = continent)) +
  geom_point(aes(y = totalPop)) +
  geom_line(aes(y = totalPop)) +
  scale_y_log10(expand = c(0, 0)) +
  scale_x_continuous(breaks = seq(1952, 2007, by = 5))
```

#Task#3

```{r}
gapminder %>%
  filter(continent == "Africa", year == 2007) %>%
  ggplot(aes(x = country, y = gdpPercap,  fill = country)) +
  geom_bar(stat = "Identity") +
  guides(fill=FALSE) +
  theme_dark() +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.3))
```

```{r}
gapminder %>%
  filter(continent == "Europe", year == 2007) %>%
  ggplot(aes(x = country, y = gdpPercap,  fill = country)) +
  geom_bar(stat = "Identity") +
  guides(fill=FALSE) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.3))
```

```{r}
gapminder %>%
  filter(continent == "Americas", year == 2007) %>%
  ggplot(aes(x = country, y = gdpPercap,  fill = country)) +
  geom_bar(stat = "Identity") +
  guides(fill=FALSE) +
  theme_get() +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.3))
```

```{r}
gapminder %>%
  filter(continent == "Asia", year == 2007) %>%
  ggplot(aes(x = country, y = gdpPercap,  fill = country)) +
  geom_bar(stat = "Identity") +
  guides(fill=FALSE) +
  theme_grey() +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.3))
```

```{r}
library(reshape)
gapminder %>%
  filter( year == 2007) %>%
  ggplot(aes(x = continent, y = lifeExp,  fill = country)) +
  geom_bar(stat = "Identity",position=position_dodge()) +
  guides(fill = FALSE) +
  theme_dark() +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.3)) 
```

```{r}
library(reshape)
gapminder %>%
  filter(continent == "Europe") %>%
  ggplot(aes(x = year, y = gdpPercap,  fill = country)) +
  geom_bar(stat = "Identity", position=position_dodge()) +
  guides(fill = FALSE) +
  theme_bw() +
  theme(axis.text.x = element_text(angle = -90, hjust = 0, vjust = 0.3)) +
  scale_x_continuous(breaks = seq(1952, 2007, by = 5))
```

