---
title: "HW_02"
author: "Oksana"
date: "05 04 2019"
output: pdf_document
---



```{r}
library(boot)
data(melanoma)
head(melanoma)
titanic <- read.csv("titanic.csv", sep = ';')
head(titanic)
```

```{r}


my_data_function <- function(your_data, rw = 0, clmn = 0) {
  if (rw == 0 && clmn == 0) {
    res <- list(subs = as.data.frame(your_data)) 
  } else if (rw == 0) {
    res <- list(subs = as.data.frame(your_data[, clmn])) 
  } else if (clmn == 0) {
    res <- list(subs = as.data.frame(your_data[rw,])) 
  } else {
    res <- list(subs = as.data.frame(your_data[rw,clmn]))
  }
  
  calc <- calculation(res)
  res <- c(res, calculus = calc)
  res
}

calculation <- function(sub_data){
  calc = list()

  for (col in colnames(sub_data$subs)) {
    if (is.numeric(sub_data$subs[[col]])) {
      tmp <- mean(sub_data$subs[[col]])
      names(tmp) <- col
      calc <- c(calc, tmp)
    } else {
      tmp <- summary(sub_data$subs[[col]])
      names_tmp <- paste0(col, names(tmp))
      names(tmp) <- names_tmp
      calc <- c(calc, tmp)
    }
  }
  return(calc)
}


```



```{r}
#Examples of subsetting and computing

###1
a <- my_data_function(melanoma, rw = 1:10, clmn = c(1,3,6))
head(a$subs)
a[-1]
###2
a <- my_data_function(melanoma, clmn = c(1,3,6))
head(a$subs)
a[-1]
###3
a <- my_data_function(melanoma, c(1,2,3))
head(a)
###4
a <- my_data_function(melanoma, clmn  = c(T,F, F, F, T, F, F))
head(a$subs)
a[-1]
###5
a <- my_data_function(melanoma, clmn = c("time", "age"))
head(a$subs)
a[-1]
###6
a <- my_data_function(melanoma, rw = 3:6)
head(a$subs)
a[-1]
###7
a <- my_data_function(melanoma, rw = c(3,4,5,6))
head(a$subs)
a[-1]
###8
a <- my_data_function(melanoma)
head(a$subs)
a[-1]
###9
a <- my_data_function(titanic, rw = 1:1000)
head(a$subs)
a[-1]

```


